// flow-typed signature: e0018e7893693b4e3f1ae68238db735d
// flow-typed version: <<STUB>>/@evercode-lab/qtumcore-lib_v^0.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@evercode-lab/qtumcore-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@evercode-lab/qtumcore-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@evercode-lab/qtumcore-lib/benchmark/script' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/benchmark/serialization' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/gulpfile' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/karma.conf' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/address' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/block/block' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/block/blockheader' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/block/index' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/block/merkleblock' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/crypto/bn' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/crypto/ecdsa' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/crypto/hash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/crypto/point' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/crypto/random' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/crypto/signature' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/encoding/base58' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/encoding/base58check' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/encoding/bufferreader' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/encoding/bufferwriter' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/encoding/varint' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/errors/index' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/errors/spec' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/hdprivatekey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/hdpublickey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/networks' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/opcode' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/privatekey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/publickey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/script/index' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/script/interpreter' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/script/script' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/index' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/index' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/input' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/multisig' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/multisigscripthash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/publickey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/publickeyhash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/output' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/sighash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/signature' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/transaction' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/transaction/unspentoutput' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/unit' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/uri' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/util/buffer' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/util/js' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/lib/util/preconditions' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/qtumcore-lib' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/qtumcore-lib.min' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/address' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/block/block' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/block/blockheader_new' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/block/blockheader' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/block/merkleblock' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/block/newblock' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/block/newblockheader' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/crypto/bn' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/crypto/ecdsa' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/crypto/hash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/crypto/point' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/crypto/random' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/crypto/signature' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/data/blk86756-testnet' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/data/blk86756-testnetnew' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/data/merkleblocks' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/data/qtum/block-pos' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/data/qtum/block-pow' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/docs' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/encoding/base58' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/encoding/base58check' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/encoding/bufferreader' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/encoding/bufferwriter' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/encoding/varint' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/hdkeys' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/hdprivatekey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/hdpublickey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/index' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/networks' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/opcode' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/privatekey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/publickey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/script/interpreter' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/script/script' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/deserialize' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/input/input' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/input/multisig' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/input/multisigscripthash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/input/publickey' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/input/publickeyhash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/newtransaction' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/output' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/sighash' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/signature' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/transaction_new' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/transaction' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/transaction/unspentoutput' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/unit' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/uri' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/util/buffer' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/util/js' {
  declare module.exports: any;
}

declare module '@evercode-lab/qtumcore-lib/test/util/preconditions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@evercode-lab/qtumcore-lib/benchmark/script.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/benchmark/script'>;
}
declare module '@evercode-lab/qtumcore-lib/benchmark/serialization.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/benchmark/serialization'>;
}
declare module '@evercode-lab/qtumcore-lib/gulpfile.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/gulpfile'>;
}
declare module '@evercode-lab/qtumcore-lib/index' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib'>;
}
declare module '@evercode-lab/qtumcore-lib/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib'>;
}
declare module '@evercode-lab/qtumcore-lib/karma.conf.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/karma.conf'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/address.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/address'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/block/block.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/block/block'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/block/blockheader.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/block/blockheader'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/block/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/block/index'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/block/merkleblock.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/block/merkleblock'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/crypto/bn.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/crypto/bn'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/crypto/ecdsa.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/crypto/ecdsa'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/crypto/hash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/crypto/hash'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/crypto/point.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/crypto/point'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/crypto/random.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/crypto/random'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/crypto/signature.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/crypto/signature'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/encoding/base58.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/encoding/base58'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/encoding/base58check.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/encoding/base58check'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/encoding/bufferreader.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/encoding/bufferreader'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/encoding/bufferwriter.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/encoding/bufferwriter'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/encoding/varint.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/encoding/varint'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/errors/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/errors/index'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/errors/spec.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/errors/spec'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/hdprivatekey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/hdprivatekey'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/hdpublickey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/hdpublickey'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/networks.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/networks'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/opcode.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/opcode'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/privatekey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/privatekey'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/publickey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/publickey'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/script/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/script/index'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/script/interpreter.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/script/interpreter'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/script/script.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/script/script'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/index'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/input/index'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/input.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/input/input'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/multisig.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/input/multisig'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/multisigscripthash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/input/multisigscripthash'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/publickey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/input/publickey'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/input/publickeyhash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/input/publickeyhash'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/output.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/output'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/sighash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/sighash'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/signature.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/signature'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/transaction.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/transaction'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/transaction/unspentoutput.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/transaction/unspentoutput'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/unit.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/unit'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/uri.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/uri'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/util/buffer.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/util/buffer'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/util/js.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/util/js'>;
}
declare module '@evercode-lab/qtumcore-lib/lib/util/preconditions.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/lib/util/preconditions'>;
}
declare module '@evercode-lab/qtumcore-lib/qtumcore-lib.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/qtumcore-lib'>;
}
declare module '@evercode-lab/qtumcore-lib/qtumcore-lib.min.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/qtumcore-lib.min'>;
}
declare module '@evercode-lab/qtumcore-lib/test/address.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/address'>;
}
declare module '@evercode-lab/qtumcore-lib/test/block/block.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/block/block'>;
}
declare module '@evercode-lab/qtumcore-lib/test/block/blockheader_new.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/block/blockheader_new'>;
}
declare module '@evercode-lab/qtumcore-lib/test/block/blockheader.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/block/blockheader'>;
}
declare module '@evercode-lab/qtumcore-lib/test/block/merkleblock.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/block/merkleblock'>;
}
declare module '@evercode-lab/qtumcore-lib/test/block/newblock.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/block/newblock'>;
}
declare module '@evercode-lab/qtumcore-lib/test/block/newblockheader.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/block/newblockheader'>;
}
declare module '@evercode-lab/qtumcore-lib/test/crypto/bn.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/crypto/bn'>;
}
declare module '@evercode-lab/qtumcore-lib/test/crypto/ecdsa.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/crypto/ecdsa'>;
}
declare module '@evercode-lab/qtumcore-lib/test/crypto/hash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/crypto/hash'>;
}
declare module '@evercode-lab/qtumcore-lib/test/crypto/point.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/crypto/point'>;
}
declare module '@evercode-lab/qtumcore-lib/test/crypto/random.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/crypto/random'>;
}
declare module '@evercode-lab/qtumcore-lib/test/crypto/signature.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/crypto/signature'>;
}
declare module '@evercode-lab/qtumcore-lib/test/data/blk86756-testnet.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/data/blk86756-testnet'>;
}
declare module '@evercode-lab/qtumcore-lib/test/data/blk86756-testnetnew.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/data/blk86756-testnetnew'>;
}
declare module '@evercode-lab/qtumcore-lib/test/data/merkleblocks.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/data/merkleblocks'>;
}
declare module '@evercode-lab/qtumcore-lib/test/data/qtum/block-pos.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/data/qtum/block-pos'>;
}
declare module '@evercode-lab/qtumcore-lib/test/data/qtum/block-pow.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/data/qtum/block-pow'>;
}
declare module '@evercode-lab/qtumcore-lib/test/docs.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/docs'>;
}
declare module '@evercode-lab/qtumcore-lib/test/encoding/base58.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/encoding/base58'>;
}
declare module '@evercode-lab/qtumcore-lib/test/encoding/base58check.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/encoding/base58check'>;
}
declare module '@evercode-lab/qtumcore-lib/test/encoding/bufferreader.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/encoding/bufferreader'>;
}
declare module '@evercode-lab/qtumcore-lib/test/encoding/bufferwriter.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/encoding/bufferwriter'>;
}
declare module '@evercode-lab/qtumcore-lib/test/encoding/varint.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/encoding/varint'>;
}
declare module '@evercode-lab/qtumcore-lib/test/hdkeys.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/hdkeys'>;
}
declare module '@evercode-lab/qtumcore-lib/test/hdprivatekey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/hdprivatekey'>;
}
declare module '@evercode-lab/qtumcore-lib/test/hdpublickey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/hdpublickey'>;
}
declare module '@evercode-lab/qtumcore-lib/test/index.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/index'>;
}
declare module '@evercode-lab/qtumcore-lib/test/networks.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/networks'>;
}
declare module '@evercode-lab/qtumcore-lib/test/opcode.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/opcode'>;
}
declare module '@evercode-lab/qtumcore-lib/test/privatekey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/privatekey'>;
}
declare module '@evercode-lab/qtumcore-lib/test/publickey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/publickey'>;
}
declare module '@evercode-lab/qtumcore-lib/test/script/interpreter.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/script/interpreter'>;
}
declare module '@evercode-lab/qtumcore-lib/test/script/script.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/script/script'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/deserialize.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/deserialize'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/input/input.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/input/input'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/input/multisig.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/input/multisig'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/input/multisigscripthash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/input/multisigscripthash'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/input/publickey.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/input/publickey'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/input/publickeyhash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/input/publickeyhash'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/newtransaction.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/newtransaction'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/output.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/output'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/sighash.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/sighash'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/signature.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/signature'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/transaction_new.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/transaction_new'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/transaction.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/transaction'>;
}
declare module '@evercode-lab/qtumcore-lib/test/transaction/unspentoutput.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/transaction/unspentoutput'>;
}
declare module '@evercode-lab/qtumcore-lib/test/unit.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/unit'>;
}
declare module '@evercode-lab/qtumcore-lib/test/uri.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/uri'>;
}
declare module '@evercode-lab/qtumcore-lib/test/util/buffer.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/util/buffer'>;
}
declare module '@evercode-lab/qtumcore-lib/test/util/js.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/util/js'>;
}
declare module '@evercode-lab/qtumcore-lib/test/util/preconditions.js' {
  declare module.exports: $Exports<'@evercode-lab/qtumcore-lib/test/util/preconditions'>;
}
