// flow-typed signature: 658522b64442bed67e2896fd08af6ffb
// flow-typed version: <<STUB>>/bitcore-mnemonic_v^1.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcore-mnemonic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcore-mnemonic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcore-mnemonic/gulpfile' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/errors' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/mnemonic' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/pbkdf2' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/chinese' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/english' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/french' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/index' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/italian' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/japanese' {
  declare module.exports: any;
}

declare module 'bitcore-mnemonic/lib/words/spanish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcore-mnemonic/gulpfile.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/gulpfile'>;
}
declare module 'bitcore-mnemonic/index' {
  declare module.exports: $Exports<'bitcore-mnemonic'>;
}
declare module 'bitcore-mnemonic/index.js' {
  declare module.exports: $Exports<'bitcore-mnemonic'>;
}
declare module 'bitcore-mnemonic/lib/errors.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/errors'>;
}
declare module 'bitcore-mnemonic/lib/mnemonic.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/mnemonic'>;
}
declare module 'bitcore-mnemonic/lib/pbkdf2.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/pbkdf2'>;
}
declare module 'bitcore-mnemonic/lib/words/chinese.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/chinese'>;
}
declare module 'bitcore-mnemonic/lib/words/english.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/english'>;
}
declare module 'bitcore-mnemonic/lib/words/french.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/french'>;
}
declare module 'bitcore-mnemonic/lib/words/index.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/index'>;
}
declare module 'bitcore-mnemonic/lib/words/italian.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/italian'>;
}
declare module 'bitcore-mnemonic/lib/words/japanese.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/japanese'>;
}
declare module 'bitcore-mnemonic/lib/words/spanish.js' {
  declare module.exports: $Exports<'bitcore-mnemonic/lib/words/spanish'>;
}
