// flow-typed signature: 74a80830675698ad8d3f0a830b7866ba
// flow-typed version: <<STUB>>/electrode-react-webapp_v^2.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-react-webapp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-react-webapp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-react-webapp/lib/custom-token' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/default-handlers' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/express/index' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/group-scripts' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/hapi/index' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/http-status' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/koa/index' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/load-handler' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/parse-template' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/react-webapp' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/render-context' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/render-output' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/renderer' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/token' {
  declare module.exports: any;
}

declare module 'electrode-react-webapp/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-react-webapp/lib/custom-token.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/custom-token'>;
}
declare module 'electrode-react-webapp/lib/default-handlers.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/default-handlers'>;
}
declare module 'electrode-react-webapp/lib/express/index.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/express/index'>;
}
declare module 'electrode-react-webapp/lib/group-scripts.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/group-scripts'>;
}
declare module 'electrode-react-webapp/lib/hapi/index.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/hapi/index'>;
}
declare module 'electrode-react-webapp/lib/http-status.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/http-status'>;
}
declare module 'electrode-react-webapp/lib/koa/index.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/koa/index'>;
}
declare module 'electrode-react-webapp/lib/load-handler.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/load-handler'>;
}
declare module 'electrode-react-webapp/lib/parse-template.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/parse-template'>;
}
declare module 'electrode-react-webapp/lib/react-webapp.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/react-webapp'>;
}
declare module 'electrode-react-webapp/lib/render-context.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/render-context'>;
}
declare module 'electrode-react-webapp/lib/render-output.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/render-output'>;
}
declare module 'electrode-react-webapp/lib/renderer.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/renderer'>;
}
declare module 'electrode-react-webapp/lib/token.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/token'>;
}
declare module 'electrode-react-webapp/lib/utils.js' {
  declare module.exports: $Exports<'electrode-react-webapp/lib/utils'>;
}
