// flow-typed signature: 6a8d1829c870f7b412a83425ae4dd9ff
// flow-typed version: <<STUB>>/electrode-confippet_v^1.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-confippet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-confippet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-confippet/config' {
  declare module.exports: any;
}

declare module 'electrode-confippet/gulpfile' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/compose-config' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/default-compose-opts' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/ext-handlers' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/index' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/preset-config' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/process-config' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/provider-types' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/store' {
  declare module.exports: any;
}

declare module 'electrode-confippet/lib/util' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/composed-result' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/config/default' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/config/production' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/spec/compose-config.spec' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/spec/preset-config.spec' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/spec/process-config.spec' {
  declare module.exports: any;
}

declare module 'electrode-confippet/test/spec/store.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-confippet/config.js' {
  declare module.exports: $Exports<'electrode-confippet/config'>;
}
declare module 'electrode-confippet/gulpfile.js' {
  declare module.exports: $Exports<'electrode-confippet/gulpfile'>;
}
declare module 'electrode-confippet/lib/compose-config.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/compose-config'>;
}
declare module 'electrode-confippet/lib/default-compose-opts.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/default-compose-opts'>;
}
declare module 'electrode-confippet/lib/ext-handlers.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/ext-handlers'>;
}
declare module 'electrode-confippet/lib/index.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/index'>;
}
declare module 'electrode-confippet/lib/preset-config.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/preset-config'>;
}
declare module 'electrode-confippet/lib/process-config.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/process-config'>;
}
declare module 'electrode-confippet/lib/provider-types.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/provider-types'>;
}
declare module 'electrode-confippet/lib/store.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/store'>;
}
declare module 'electrode-confippet/lib/util.js' {
  declare module.exports: $Exports<'electrode-confippet/lib/util'>;
}
declare module 'electrode-confippet/test/composed-result.js' {
  declare module.exports: $Exports<'electrode-confippet/test/composed-result'>;
}
declare module 'electrode-confippet/test/config/default.js' {
  declare module.exports: $Exports<'electrode-confippet/test/config/default'>;
}
declare module 'electrode-confippet/test/config/production.js' {
  declare module.exports: $Exports<'electrode-confippet/test/config/production'>;
}
declare module 'electrode-confippet/test/spec/compose-config.spec.js' {
  declare module.exports: $Exports<'electrode-confippet/test/spec/compose-config.spec'>;
}
declare module 'electrode-confippet/test/spec/preset-config.spec.js' {
  declare module.exports: $Exports<'electrode-confippet/test/spec/preset-config.spec'>;
}
declare module 'electrode-confippet/test/spec/process-config.spec.js' {
  declare module.exports: $Exports<'electrode-confippet/test/spec/process-config.spec'>;
}
declare module 'electrode-confippet/test/spec/store.spec.js' {
  declare module.exports: $Exports<'electrode-confippet/test/spec/store.spec'>;
}
