// flow-typed signature: 81848a8e375ce8f2f3c44c95fffa1e1c
// flow-typed version: <<STUB>>/electrode-auto-ssr_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-auto-ssr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-auto-ssr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-auto-ssr/lib/autossr' {
  declare module.exports: any;
}

declare module 'electrode-auto-ssr/lib/conditions/machine-info' {
  declare module.exports: any;
}

declare module 'electrode-auto-ssr/lib/conditions/machine-load' {
  declare module.exports: any;
}

declare module 'electrode-auto-ssr/lib/conditions/response-time' {
  declare module.exports: any;
}

declare module 'electrode-auto-ssr/lib/conditions/server-load' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-auto-ssr/lib/autossr.js' {
  declare module.exports: $Exports<'electrode-auto-ssr/lib/autossr'>;
}
declare module 'electrode-auto-ssr/lib/conditions/machine-info.js' {
  declare module.exports: $Exports<'electrode-auto-ssr/lib/conditions/machine-info'>;
}
declare module 'electrode-auto-ssr/lib/conditions/machine-load.js' {
  declare module.exports: $Exports<'electrode-auto-ssr/lib/conditions/machine-load'>;
}
declare module 'electrode-auto-ssr/lib/conditions/response-time.js' {
  declare module.exports: $Exports<'electrode-auto-ssr/lib/conditions/response-time'>;
}
declare module 'electrode-auto-ssr/lib/conditions/server-load.js' {
  declare module.exports: $Exports<'electrode-auto-ssr/lib/conditions/server-load'>;
}
