// flow-typed signature: 9ed98ee4491979cbe7f965d7e8c99e80
// flow-typed version: <<STUB>>/qtumjs_v^1.4.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qtumjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qtumjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qtumjs/dist/qtum' {
  declare module.exports: any;
}

declare module 'qtumjs/doc/assets/js/main' {
  declare module.exports: any;
}

declare module 'qtumjs/doc/assets/js/search' {
  declare module.exports: any;
}

declare module 'qtumjs/example/setA' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/abi' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/ConfirmedTransaction' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/Contract' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/ContractSendReceipt' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/ContractSendTx' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/ethjs-abi' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/EventsSubscriber' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/index' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/LogsSubscriber' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/QtumRPC' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/QtumRPCRaw' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/sleep' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/TransactionPromise' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/TxPromise' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/TxReceipt' {
  declare module.exports: any;
}

declare module 'qtumjs/lib/TxReceiptPromise' {
  declare module.exports: any;
}

declare module 'qtumjs/package/dist/qtum' {
  declare module.exports: any;
}

declare module 'qtumjs/package/doc/assets/js/main' {
  declare module.exports: any;
}

declare module 'qtumjs/package/doc/assets/js/search' {
  declare module.exports: any;
}

declare module 'qtumjs/package/example/setA' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/abi' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/ConfirmedTransaction' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/Contract' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/ContractSendReceipt' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/ContractSendTx' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/ethjs-abi' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/EventsSubscriber' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/index' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/LogsSubscriber' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/QtumRPC' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/QtumRPCRaw' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/sleep' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/TransactionPromise' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/TxPromise' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/TxReceipt' {
  declare module.exports: any;
}

declare module 'qtumjs/package/lib/TxReceiptPromise' {
  declare module.exports: any;
}

declare module 'qtumjs/package/webpack.config' {
  declare module.exports: any;
}

declare module 'qtumjs/producer11' {
  declare module.exports: any;
}

declare module 'qtumjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qtumjs/dist/qtum.js' {
  declare module.exports: $Exports<'qtumjs/dist/qtum'>;
}
declare module 'qtumjs/doc/assets/js/main.js' {
  declare module.exports: $Exports<'qtumjs/doc/assets/js/main'>;
}
declare module 'qtumjs/doc/assets/js/search.js' {
  declare module.exports: $Exports<'qtumjs/doc/assets/js/search'>;
}
declare module 'qtumjs/example/setA.js' {
  declare module.exports: $Exports<'qtumjs/example/setA'>;
}
declare module 'qtumjs/lib/abi.js' {
  declare module.exports: $Exports<'qtumjs/lib/abi'>;
}
declare module 'qtumjs/lib/ConfirmedTransaction.js' {
  declare module.exports: $Exports<'qtumjs/lib/ConfirmedTransaction'>;
}
declare module 'qtumjs/lib/Contract.js' {
  declare module.exports: $Exports<'qtumjs/lib/Contract'>;
}
declare module 'qtumjs/lib/ContractSendReceipt.js' {
  declare module.exports: $Exports<'qtumjs/lib/ContractSendReceipt'>;
}
declare module 'qtumjs/lib/ContractSendTx.js' {
  declare module.exports: $Exports<'qtumjs/lib/ContractSendTx'>;
}
declare module 'qtumjs/lib/ethjs-abi.js' {
  declare module.exports: $Exports<'qtumjs/lib/ethjs-abi'>;
}
declare module 'qtumjs/lib/EventsSubscriber.js' {
  declare module.exports: $Exports<'qtumjs/lib/EventsSubscriber'>;
}
declare module 'qtumjs/lib/index.js' {
  declare module.exports: $Exports<'qtumjs/lib/index'>;
}
declare module 'qtumjs/lib/LogsSubscriber.js' {
  declare module.exports: $Exports<'qtumjs/lib/LogsSubscriber'>;
}
declare module 'qtumjs/lib/QtumRPC.js' {
  declare module.exports: $Exports<'qtumjs/lib/QtumRPC'>;
}
declare module 'qtumjs/lib/QtumRPCRaw.js' {
  declare module.exports: $Exports<'qtumjs/lib/QtumRPCRaw'>;
}
declare module 'qtumjs/lib/sleep.js' {
  declare module.exports: $Exports<'qtumjs/lib/sleep'>;
}
declare module 'qtumjs/lib/TransactionPromise.js' {
  declare module.exports: $Exports<'qtumjs/lib/TransactionPromise'>;
}
declare module 'qtumjs/lib/TxPromise.js' {
  declare module.exports: $Exports<'qtumjs/lib/TxPromise'>;
}
declare module 'qtumjs/lib/TxReceipt.js' {
  declare module.exports: $Exports<'qtumjs/lib/TxReceipt'>;
}
declare module 'qtumjs/lib/TxReceiptPromise.js' {
  declare module.exports: $Exports<'qtumjs/lib/TxReceiptPromise'>;
}
declare module 'qtumjs/package/dist/qtum.js' {
  declare module.exports: $Exports<'qtumjs/package/dist/qtum'>;
}
declare module 'qtumjs/package/doc/assets/js/main.js' {
  declare module.exports: $Exports<'qtumjs/package/doc/assets/js/main'>;
}
declare module 'qtumjs/package/doc/assets/js/search.js' {
  declare module.exports: $Exports<'qtumjs/package/doc/assets/js/search'>;
}
declare module 'qtumjs/package/example/setA.js' {
  declare module.exports: $Exports<'qtumjs/package/example/setA'>;
}
declare module 'qtumjs/package/lib/abi.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/abi'>;
}
declare module 'qtumjs/package/lib/ConfirmedTransaction.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/ConfirmedTransaction'>;
}
declare module 'qtumjs/package/lib/Contract.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/Contract'>;
}
declare module 'qtumjs/package/lib/ContractSendReceipt.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/ContractSendReceipt'>;
}
declare module 'qtumjs/package/lib/ContractSendTx.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/ContractSendTx'>;
}
declare module 'qtumjs/package/lib/ethjs-abi.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/ethjs-abi'>;
}
declare module 'qtumjs/package/lib/EventsSubscriber.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/EventsSubscriber'>;
}
declare module 'qtumjs/package/lib/index.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/index'>;
}
declare module 'qtumjs/package/lib/LogsSubscriber.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/LogsSubscriber'>;
}
declare module 'qtumjs/package/lib/QtumRPC.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/QtumRPC'>;
}
declare module 'qtumjs/package/lib/QtumRPCRaw.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/QtumRPCRaw'>;
}
declare module 'qtumjs/package/lib/sleep.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/sleep'>;
}
declare module 'qtumjs/package/lib/TransactionPromise.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/TransactionPromise'>;
}
declare module 'qtumjs/package/lib/TxPromise.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/TxPromise'>;
}
declare module 'qtumjs/package/lib/TxReceipt.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/TxReceipt'>;
}
declare module 'qtumjs/package/lib/TxReceiptPromise.js' {
  declare module.exports: $Exports<'qtumjs/package/lib/TxReceiptPromise'>;
}
declare module 'qtumjs/package/webpack.config.js' {
  declare module.exports: $Exports<'qtumjs/package/webpack.config'>;
}
declare module 'qtumjs/producer11.js' {
  declare module.exports: $Exports<'qtumjs/producer11'>;
}
declare module 'qtumjs/webpack.config.js' {
  declare module.exports: $Exports<'qtumjs/webpack.config'>;
}
