// flow-typed signature: 615ac739b54655104b938f578aa1ffcf
// flow-typed version: <<STUB>>/react-redux-i18n_v^1.9.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-i18n/build/actions' {
  declare module.exports: any;
}

declare module 'react-redux-i18n/build/index' {
  declare module.exports: any;
}

declare module 'react-redux-i18n/build/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-i18n/build/actions.js' {
  declare module.exports: $Exports<'react-redux-i18n/build/actions'>;
}
declare module 'react-redux-i18n/build/index.js' {
  declare module.exports: $Exports<'react-redux-i18n/build/index'>;
}
declare module 'react-redux-i18n/build/reducer.js' {
  declare module.exports: $Exports<'react-redux-i18n/build/reducer'>;
}
