// flow-typed signature: 11bb5c31913f870a7eef10efc1519965
// flow-typed version: <<STUB>>/react-load-image_v^0.1.6/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-load-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-load-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-load-image/example/dist' {
  declare module.exports: any;
}

declare module 'react-load-image/example/example' {
  declare module.exports: any;
}

declare module 'react-load-image/lib/index' {
  declare module.exports: any;
}

declare module 'react-load-image/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-load-image/example/dist.js' {
  declare module.exports: $Exports<'react-load-image/example/dist'>;
}
declare module 'react-load-image/example/example.js' {
  declare module.exports: $Exports<'react-load-image/example/example'>;
}
declare module 'react-load-image/lib/index.js' {
  declare module.exports: $Exports<'react-load-image/lib/index'>;
}
declare module 'react-load-image/webpack.config.js' {
  declare module.exports: $Exports<'react-load-image/webpack.config'>;
}
