// flow-typed signature: 049fd3c1c067a07e3abef1654cbcda4d
// flow-typed version: <<STUB>>/react-dates_v^16.2.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dates/_gh-pages/static/manager.00caad351fdd073c07bb.bundle' {
  declare module.exports: any;
}

declare module 'react-dates/_gh-pages/static/preview.72f79b32696e01083a23.bundle' {
  declare module.exports: any;
}

declare module 'react-dates/constants' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CalendarIcon' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CalendarWeek' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/ChevronDown' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/ChevronUp' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/CustomizableCalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DayPickerKeyboardShortcuts' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/DayPickerSingleDateController' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/KeyboardShortcutRow' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/LeftArrow' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/OutsideClickHandler' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/RightArrow' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates/esm/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/esm/constants' {
  declare module.exports: any;
}

declare module 'react-dates/esm/defaultPhrases' {
  declare module.exports: any;
}

declare module 'react-dates/esm/index' {
  declare module.exports: any;
}

declare module 'react-dates/esm/initialize' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/DayOfWeekShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/IconPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/OpenDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/ScrollableOrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/esm/theme/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/calculateDimension' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getCalendarDaySettings' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getCalendarMonthWidth' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getInputHeight' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getPhrase' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getPhrasePropTypes' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getSelectedDateOffset' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/getVisibleDays' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isDayVisible' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/registerCSSInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/registerInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/toISOMonthString' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates/esm/utils/toMomentObject' {
  declare module.exports: any;
}

declare module 'react-dates/initialize' {
  declare module.exports: any;
}

declare module 'react-dates/karma.conf' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarIcon' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CalendarWeek' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/ChevronDown' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/ChevronUp' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/CustomizableCalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPickerKeyboardShortcuts' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/DayPickerSingleDateController' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/KeyboardShortcutRow' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/LeftArrow' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/OutsideClickHandler' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/RightArrow' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates/lib/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/lib/constants' {
  declare module.exports: any;
}

declare module 'react-dates/lib/defaultPhrases' {
  declare module.exports: any;
}

declare module 'react-dates/lib/index' {
  declare module.exports: any;
}

declare module 'react-dates/lib/initialize' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/DayOfWeekShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/IconPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/OpenDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/ScrollableOrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/lib/theme/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/calculateDimension' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getCalendarDaySettings' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getCalendarMonthWidth' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getInputHeight' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getPhrase' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getPhrasePropTypes' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getSelectedDateOffset' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/getVisibleDays' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isDayVisible' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/registerCSSInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/registerInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toISOMonthString' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates/lib/utils/toMomentObject' {
  declare module.exports: any;
}

declare module 'react-dates/scripts/buildCSS' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarIcon' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CalendarWeek' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/ChevronDown' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/ChevronUp' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/CustomizableCalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPickerKeyboardShortcuts' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/DayPickerSingleDateController' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/KeyboardShortcutRow' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/LeftArrow' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/OutsideClickHandler' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/RightArrow' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates/src/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates/src/constants' {
  declare module.exports: any;
}

declare module 'react-dates/src/defaultPhrases' {
  declare module.exports: any;
}

declare module 'react-dates/src/index' {
  declare module.exports: any;
}

declare module 'react-dates/src/initialize' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/DayOfWeekShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/IconPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/OpenDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/ScrollableOrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates/src/theme/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/calculateDimension' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getCalendarDaySettings' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getCalendarMonthWidth' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getInputHeight' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getPhrase' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getPhrasePropTypes' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getSelectedDateOffset' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/getVisibleDays' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isDayVisible' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/registerCSSInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/registerInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toISOMonthString' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates/src/utils/toMomentObject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dates/_gh-pages/static/manager.00caad351fdd073c07bb.bundle.js' {
  declare module.exports: $Exports<'react-dates/_gh-pages/static/manager.00caad351fdd073c07bb.bundle'>;
}
declare module 'react-dates/_gh-pages/static/preview.72f79b32696e01083a23.bundle.js' {
  declare module.exports: $Exports<'react-dates/_gh-pages/static/preview.72f79b32696e01083a23.bundle'>;
}
declare module 'react-dates/constants.js' {
  declare module.exports: $Exports<'react-dates/constants'>;
}
declare module 'react-dates/esm/components/CalendarDay.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CalendarDay'>;
}
declare module 'react-dates/esm/components/CalendarIcon.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CalendarIcon'>;
}
declare module 'react-dates/esm/components/CalendarMonth.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CalendarMonth'>;
}
declare module 'react-dates/esm/components/CalendarMonthGrid.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CalendarMonthGrid'>;
}
declare module 'react-dates/esm/components/CalendarWeek.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CalendarWeek'>;
}
declare module 'react-dates/esm/components/ChevronDown.js' {
  declare module.exports: $Exports<'react-dates/esm/components/ChevronDown'>;
}
declare module 'react-dates/esm/components/ChevronUp.js' {
  declare module.exports: $Exports<'react-dates/esm/components/ChevronUp'>;
}
declare module 'react-dates/esm/components/CloseButton.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CloseButton'>;
}
declare module 'react-dates/esm/components/CustomizableCalendarDay.js' {
  declare module.exports: $Exports<'react-dates/esm/components/CustomizableCalendarDay'>;
}
declare module 'react-dates/esm/components/DateInput.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DateInput'>;
}
declare module 'react-dates/esm/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DateRangePicker'>;
}
declare module 'react-dates/esm/components/DateRangePickerInput.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DateRangePickerInput'>;
}
declare module 'react-dates/esm/components/DateRangePickerInputController.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DateRangePickerInputController'>;
}
declare module 'react-dates/esm/components/DayPicker.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DayPicker'>;
}
declare module 'react-dates/esm/components/DayPickerKeyboardShortcuts.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DayPickerKeyboardShortcuts'>;
}
declare module 'react-dates/esm/components/DayPickerNavigation.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DayPickerNavigation'>;
}
declare module 'react-dates/esm/components/DayPickerRangeController.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DayPickerRangeController'>;
}
declare module 'react-dates/esm/components/DayPickerSingleDateController.js' {
  declare module.exports: $Exports<'react-dates/esm/components/DayPickerSingleDateController'>;
}
declare module 'react-dates/esm/components/KeyboardShortcutRow.js' {
  declare module.exports: $Exports<'react-dates/esm/components/KeyboardShortcutRow'>;
}
declare module 'react-dates/esm/components/LeftArrow.js' {
  declare module.exports: $Exports<'react-dates/esm/components/LeftArrow'>;
}
declare module 'react-dates/esm/components/OutsideClickHandler.js' {
  declare module.exports: $Exports<'react-dates/esm/components/OutsideClickHandler'>;
}
declare module 'react-dates/esm/components/RightArrow.js' {
  declare module.exports: $Exports<'react-dates/esm/components/RightArrow'>;
}
declare module 'react-dates/esm/components/SingleDatePicker.js' {
  declare module.exports: $Exports<'react-dates/esm/components/SingleDatePicker'>;
}
declare module 'react-dates/esm/components/SingleDatePickerInput.js' {
  declare module.exports: $Exports<'react-dates/esm/components/SingleDatePickerInput'>;
}
declare module 'react-dates/esm/constants.js' {
  declare module.exports: $Exports<'react-dates/esm/constants'>;
}
declare module 'react-dates/esm/defaultPhrases.js' {
  declare module.exports: $Exports<'react-dates/esm/defaultPhrases'>;
}
declare module 'react-dates/esm/index.js' {
  declare module.exports: $Exports<'react-dates/esm/index'>;
}
declare module 'react-dates/esm/initialize.js' {
  declare module.exports: $Exports<'react-dates/esm/initialize'>;
}
declare module 'react-dates/esm/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates/esm/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/DateRangePickerShape'>;
}
declare module 'react-dates/esm/shapes/DayOfWeekShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/DayOfWeekShape'>;
}
declare module 'react-dates/esm/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/FocusedInputShape'>;
}
declare module 'react-dates/esm/shapes/IconPositionShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/IconPositionShape'>;
}
declare module 'react-dates/esm/shapes/OpenDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/OpenDirectionShape'>;
}
declare module 'react-dates/esm/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/OrientationShape'>;
}
declare module 'react-dates/esm/shapes/ScrollableOrientationShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/ScrollableOrientationShape'>;
}
declare module 'react-dates/esm/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates/esm/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates/esm/theme/DefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/esm/theme/DefaultTheme'>;
}
declare module 'react-dates/esm/utils/calculateDimension.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/calculateDimension'>;
}
declare module 'react-dates/esm/utils/getActiveElement.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getActiveElement'>;
}
declare module 'react-dates/esm/utils/getCalendarDaySettings.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getCalendarDaySettings'>;
}
declare module 'react-dates/esm/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates/esm/utils/getCalendarMonthWidth.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getCalendarMonthWidth'>;
}
declare module 'react-dates/esm/utils/getInputHeight.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getInputHeight'>;
}
declare module 'react-dates/esm/utils/getPhrase.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getPhrase'>;
}
declare module 'react-dates/esm/utils/getPhrasePropTypes.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getPhrasePropTypes'>;
}
declare module 'react-dates/esm/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates/esm/utils/getSelectedDateOffset.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getSelectedDateOffset'>;
}
declare module 'react-dates/esm/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getTransformStyles'>;
}
declare module 'react-dates/esm/utils/getVisibleDays.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/getVisibleDays'>;
}
declare module 'react-dates/esm/utils/isAfterDay.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isAfterDay'>;
}
declare module 'react-dates/esm/utils/isBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isBeforeDay'>;
}
declare module 'react-dates/esm/utils/isDayVisible.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isDayVisible'>;
}
declare module 'react-dates/esm/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates/esm/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates/esm/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isNextDay'>;
}
declare module 'react-dates/esm/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isSameDay'>;
}
declare module 'react-dates/esm/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/isTransitionEndSupported'>;
}
declare module 'react-dates/esm/utils/registerCSSInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/registerCSSInterfaceWithDefaultTheme'>;
}
declare module 'react-dates/esm/utils/registerInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/registerInterfaceWithDefaultTheme'>;
}
declare module 'react-dates/esm/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/toISODateString'>;
}
declare module 'react-dates/esm/utils/toISOMonthString.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/toISOMonthString'>;
}
declare module 'react-dates/esm/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/toLocalizedDateString'>;
}
declare module 'react-dates/esm/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates/esm/utils/toMomentObject'>;
}
declare module 'react-dates/index' {
  declare module.exports: $Exports<'react-dates'>;
}
declare module 'react-dates/index.js' {
  declare module.exports: $Exports<'react-dates'>;
}
declare module 'react-dates/initialize.js' {
  declare module.exports: $Exports<'react-dates/initialize'>;
}
declare module 'react-dates/karma.conf.js' {
  declare module.exports: $Exports<'react-dates/karma.conf'>;
}
declare module 'react-dates/lib/components/CalendarDay.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarDay'>;
}
declare module 'react-dates/lib/components/CalendarIcon.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarIcon'>;
}
declare module 'react-dates/lib/components/CalendarMonth.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarMonth'>;
}
declare module 'react-dates/lib/components/CalendarMonthGrid.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarMonthGrid'>;
}
declare module 'react-dates/lib/components/CalendarWeek.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CalendarWeek'>;
}
declare module 'react-dates/lib/components/ChevronDown.js' {
  declare module.exports: $Exports<'react-dates/lib/components/ChevronDown'>;
}
declare module 'react-dates/lib/components/ChevronUp.js' {
  declare module.exports: $Exports<'react-dates/lib/components/ChevronUp'>;
}
declare module 'react-dates/lib/components/CloseButton.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CloseButton'>;
}
declare module 'react-dates/lib/components/CustomizableCalendarDay.js' {
  declare module.exports: $Exports<'react-dates/lib/components/CustomizableCalendarDay'>;
}
declare module 'react-dates/lib/components/DateInput.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateInput'>;
}
declare module 'react-dates/lib/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateRangePicker'>;
}
declare module 'react-dates/lib/components/DateRangePickerInput.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateRangePickerInput'>;
}
declare module 'react-dates/lib/components/DateRangePickerInputController.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DateRangePickerInputController'>;
}
declare module 'react-dates/lib/components/DayPicker.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPicker'>;
}
declare module 'react-dates/lib/components/DayPickerKeyboardShortcuts.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPickerKeyboardShortcuts'>;
}
declare module 'react-dates/lib/components/DayPickerNavigation.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPickerNavigation'>;
}
declare module 'react-dates/lib/components/DayPickerRangeController.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPickerRangeController'>;
}
declare module 'react-dates/lib/components/DayPickerSingleDateController.js' {
  declare module.exports: $Exports<'react-dates/lib/components/DayPickerSingleDateController'>;
}
declare module 'react-dates/lib/components/KeyboardShortcutRow.js' {
  declare module.exports: $Exports<'react-dates/lib/components/KeyboardShortcutRow'>;
}
declare module 'react-dates/lib/components/LeftArrow.js' {
  declare module.exports: $Exports<'react-dates/lib/components/LeftArrow'>;
}
declare module 'react-dates/lib/components/OutsideClickHandler.js' {
  declare module.exports: $Exports<'react-dates/lib/components/OutsideClickHandler'>;
}
declare module 'react-dates/lib/components/RightArrow.js' {
  declare module.exports: $Exports<'react-dates/lib/components/RightArrow'>;
}
declare module 'react-dates/lib/components/SingleDatePicker.js' {
  declare module.exports: $Exports<'react-dates/lib/components/SingleDatePicker'>;
}
declare module 'react-dates/lib/components/SingleDatePickerInput.js' {
  declare module.exports: $Exports<'react-dates/lib/components/SingleDatePickerInput'>;
}
declare module 'react-dates/lib/constants.js' {
  declare module.exports: $Exports<'react-dates/lib/constants'>;
}
declare module 'react-dates/lib/defaultPhrases.js' {
  declare module.exports: $Exports<'react-dates/lib/defaultPhrases'>;
}
declare module 'react-dates/lib/index.js' {
  declare module.exports: $Exports<'react-dates/lib/index'>;
}
declare module 'react-dates/lib/initialize.js' {
  declare module.exports: $Exports<'react-dates/lib/initialize'>;
}
declare module 'react-dates/lib/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates/lib/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/DateRangePickerShape'>;
}
declare module 'react-dates/lib/shapes/DayOfWeekShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/DayOfWeekShape'>;
}
declare module 'react-dates/lib/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/FocusedInputShape'>;
}
declare module 'react-dates/lib/shapes/IconPositionShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/IconPositionShape'>;
}
declare module 'react-dates/lib/shapes/OpenDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/OpenDirectionShape'>;
}
declare module 'react-dates/lib/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/OrientationShape'>;
}
declare module 'react-dates/lib/shapes/ScrollableOrientationShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/ScrollableOrientationShape'>;
}
declare module 'react-dates/lib/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates/lib/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates/lib/theme/DefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/lib/theme/DefaultTheme'>;
}
declare module 'react-dates/lib/utils/calculateDimension.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/calculateDimension'>;
}
declare module 'react-dates/lib/utils/getActiveElement.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getActiveElement'>;
}
declare module 'react-dates/lib/utils/getCalendarDaySettings.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getCalendarDaySettings'>;
}
declare module 'react-dates/lib/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates/lib/utils/getCalendarMonthWidth.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getCalendarMonthWidth'>;
}
declare module 'react-dates/lib/utils/getInputHeight.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getInputHeight'>;
}
declare module 'react-dates/lib/utils/getPhrase.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getPhrase'>;
}
declare module 'react-dates/lib/utils/getPhrasePropTypes.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getPhrasePropTypes'>;
}
declare module 'react-dates/lib/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates/lib/utils/getSelectedDateOffset.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getSelectedDateOffset'>;
}
declare module 'react-dates/lib/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getTransformStyles'>;
}
declare module 'react-dates/lib/utils/getVisibleDays.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/getVisibleDays'>;
}
declare module 'react-dates/lib/utils/isAfterDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isAfterDay'>;
}
declare module 'react-dates/lib/utils/isBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isBeforeDay'>;
}
declare module 'react-dates/lib/utils/isDayVisible.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isDayVisible'>;
}
declare module 'react-dates/lib/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates/lib/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates/lib/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isNextDay'>;
}
declare module 'react-dates/lib/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isSameDay'>;
}
declare module 'react-dates/lib/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/isTransitionEndSupported'>;
}
declare module 'react-dates/lib/utils/registerCSSInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/registerCSSInterfaceWithDefaultTheme'>;
}
declare module 'react-dates/lib/utils/registerInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/registerInterfaceWithDefaultTheme'>;
}
declare module 'react-dates/lib/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toISODateString'>;
}
declare module 'react-dates/lib/utils/toISOMonthString.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toISOMonthString'>;
}
declare module 'react-dates/lib/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toLocalizedDateString'>;
}
declare module 'react-dates/lib/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates/lib/utils/toMomentObject'>;
}
declare module 'react-dates/scripts/buildCSS.js' {
  declare module.exports: $Exports<'react-dates/scripts/buildCSS'>;
}
declare module 'react-dates/src/components/CalendarDay.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarDay'>;
}
declare module 'react-dates/src/components/CalendarIcon.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarIcon'>;
}
declare module 'react-dates/src/components/CalendarMonth.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarMonth'>;
}
declare module 'react-dates/src/components/CalendarMonthGrid.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarMonthGrid'>;
}
declare module 'react-dates/src/components/CalendarWeek.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CalendarWeek'>;
}
declare module 'react-dates/src/components/ChevronDown.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/ChevronDown'>;
}
declare module 'react-dates/src/components/ChevronUp.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/ChevronUp'>;
}
declare module 'react-dates/src/components/CloseButton.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CloseButton'>;
}
declare module 'react-dates/src/components/CustomizableCalendarDay.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/CustomizableCalendarDay'>;
}
declare module 'react-dates/src/components/DateInput.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateInput'>;
}
declare module 'react-dates/src/components/DateRangePicker.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateRangePicker'>;
}
declare module 'react-dates/src/components/DateRangePickerInput.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateRangePickerInput'>;
}
declare module 'react-dates/src/components/DateRangePickerInputController.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DateRangePickerInputController'>;
}
declare module 'react-dates/src/components/DayPicker.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPicker'>;
}
declare module 'react-dates/src/components/DayPickerKeyboardShortcuts.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPickerKeyboardShortcuts'>;
}
declare module 'react-dates/src/components/DayPickerNavigation.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPickerNavigation'>;
}
declare module 'react-dates/src/components/DayPickerRangeController.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPickerRangeController'>;
}
declare module 'react-dates/src/components/DayPickerSingleDateController.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/DayPickerSingleDateController'>;
}
declare module 'react-dates/src/components/KeyboardShortcutRow.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/KeyboardShortcutRow'>;
}
declare module 'react-dates/src/components/LeftArrow.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/LeftArrow'>;
}
declare module 'react-dates/src/components/OutsideClickHandler.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/OutsideClickHandler'>;
}
declare module 'react-dates/src/components/RightArrow.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/RightArrow'>;
}
declare module 'react-dates/src/components/SingleDatePicker.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/SingleDatePicker'>;
}
declare module 'react-dates/src/components/SingleDatePickerInput.jsx' {
  declare module.exports: $Exports<'react-dates/src/components/SingleDatePickerInput'>;
}
declare module 'react-dates/src/constants.js' {
  declare module.exports: $Exports<'react-dates/src/constants'>;
}
declare module 'react-dates/src/defaultPhrases.js' {
  declare module.exports: $Exports<'react-dates/src/defaultPhrases'>;
}
declare module 'react-dates/src/index.js' {
  declare module.exports: $Exports<'react-dates/src/index'>;
}
declare module 'react-dates/src/initialize.js' {
  declare module.exports: $Exports<'react-dates/src/initialize'>;
}
declare module 'react-dates/src/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates/src/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/DateRangePickerShape'>;
}
declare module 'react-dates/src/shapes/DayOfWeekShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/DayOfWeekShape'>;
}
declare module 'react-dates/src/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/FocusedInputShape'>;
}
declare module 'react-dates/src/shapes/IconPositionShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/IconPositionShape'>;
}
declare module 'react-dates/src/shapes/OpenDirectionShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/OpenDirectionShape'>;
}
declare module 'react-dates/src/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/OrientationShape'>;
}
declare module 'react-dates/src/shapes/ScrollableOrientationShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/ScrollableOrientationShape'>;
}
declare module 'react-dates/src/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates/src/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates/src/theme/DefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/src/theme/DefaultTheme'>;
}
declare module 'react-dates/src/utils/calculateDimension.js' {
  declare module.exports: $Exports<'react-dates/src/utils/calculateDimension'>;
}
declare module 'react-dates/src/utils/getActiveElement.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getActiveElement'>;
}
declare module 'react-dates/src/utils/getCalendarDaySettings.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getCalendarDaySettings'>;
}
declare module 'react-dates/src/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates/src/utils/getCalendarMonthWidth.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getCalendarMonthWidth'>;
}
declare module 'react-dates/src/utils/getInputHeight.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getInputHeight'>;
}
declare module 'react-dates/src/utils/getPhrase.jsx' {
  declare module.exports: $Exports<'react-dates/src/utils/getPhrase'>;
}
declare module 'react-dates/src/utils/getPhrasePropTypes.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getPhrasePropTypes'>;
}
declare module 'react-dates/src/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates/src/utils/getSelectedDateOffset.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getSelectedDateOffset'>;
}
declare module 'react-dates/src/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getTransformStyles'>;
}
declare module 'react-dates/src/utils/getVisibleDays.js' {
  declare module.exports: $Exports<'react-dates/src/utils/getVisibleDays'>;
}
declare module 'react-dates/src/utils/isAfterDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isAfterDay'>;
}
declare module 'react-dates/src/utils/isBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isBeforeDay'>;
}
declare module 'react-dates/src/utils/isDayVisible.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isDayVisible'>;
}
declare module 'react-dates/src/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates/src/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates/src/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isNextDay'>;
}
declare module 'react-dates/src/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isSameDay'>;
}
declare module 'react-dates/src/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates/src/utils/isTransitionEndSupported'>;
}
declare module 'react-dates/src/utils/registerCSSInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/src/utils/registerCSSInterfaceWithDefaultTheme'>;
}
declare module 'react-dates/src/utils/registerInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates/src/utils/registerInterfaceWithDefaultTheme'>;
}
declare module 'react-dates/src/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toISODateString'>;
}
declare module 'react-dates/src/utils/toISOMonthString.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toISOMonthString'>;
}
declare module 'react-dates/src/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toLocalizedDateString'>;
}
declare module 'react-dates/src/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates/src/utils/toMomentObject'>;
}
