// flow-typed signature: 0af063ecfbedf5905c24b25c5c1bcb4a
// flow-typed version: <<STUB>>/web3-eth_v^1.0.0-beta.27/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-eth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-eth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-eth/src/getNetworkType' {
  declare module.exports: any;
}

declare module 'web3-eth/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-eth/src/getNetworkType.js' {
  declare module.exports: $Exports<'web3-eth/src/getNetworkType'>;
}
declare module 'web3-eth/src/index.js' {
  declare module.exports: $Exports<'web3-eth/src/index'>;
}
