// flow-typed signature: a4f69760d861159d7438b99d16536c87
// flow-typed version: <<STUB>>/xclap-cli_v^0.1.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xclap-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xclap-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xclap-cli/clap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xclap-cli/clap.js' {
  declare module.exports: $Exports<'xclap-cli/clap'>;
}
